const goats = [
  {
    id: 'goat1',
    name: 'billy',
    disposition: 'rude',
    imageUrl: 'https://images2.minutemediacdn.com/image/upload/c_crop,h_843,w_1500,x_0,y_10/f_auto,q_auto,w_1100/v1555172614/shape/mentalfloss/iStock-177369626_1.jpg',
    fullness: 67,
    favPose: 'downward facing dog',
    isFainting: true,
    color: 'brown',
  },
  {
    id: 'goat2',
    name: 'willy',
    disposition: 'sweet',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Hausziege_04.jpg',
    fullness: 50,
    favPose: 'tree pose',
    isFainting: false,
    color: 'white',
  },
  {
    id: 'goat3',
    name: 'waylon',
    disposition: 'feisty',
    imageUrl: 'https://cdn.vox-cdn.com/thumbor/QuO4OXij6CKiWk49qmSxBz4RHE0=/0x79:1200x925/1200x800/filters:focal(540x268:732x460)/cdn.vox-cdn.com/uploads/chorus_image/image/61759449/cool_goat_2.0.jpg',
    fullness: 27,
    favPose: 'warrior pose',
    isFainting: false,
    color: 'pink',
  },
  {
    id: 'goat4',
    name: 'hank',
    disposition: 'shy',
    imageUrl: 'https://cdn-image.foodandwine.com/sites/default/files/styles/4_3_horizontal_-_1200x900/public/goat-milk-explainer-ft-blog0717_1.jpg?itok=n9XXBl1r',
    fullness: 99,
    favPose: 'shavasana',
    isFainting: true,
    color: 'green',
  },
  {
    id: 'goat5',
    name: 'hank jr.',
    disposition: 'flirty',
    imageUrl: 'http://cdn.shopify.com/s/files/1/0804/6487/products/you_goat_mail_3_grande.jpg?v=1551304270',
    fullness: 80,
    favPose: 'tree pose',
    isFainting: false,
    color: 'rainbow',
  },
];

export default goats;
